### ISSUE TITLE
Equipment questions

### ISSUE THREAD

**Issue by dieselrabbit** [bdraco/screenlogic_dumps#1]
Hello,
Thank you for the dumps!
A few questions:

1. It appears that all these pools have Intellibright lights, is that true?
2. `0D-BF-7F` and `0F-5A-03` have something in common that the other two don't, but it's an unknown flag. Could you guess/know what it is?

Thanks for your time.

**Comment by bdraco** [comment]
Sent from my Mobile

> On Mar 21, 2021, at 12:13 PM, Kevin Worrel ***@***.***> wrote:
> 
> ﻿
> Hello,
> Thank you for the dumps!
> A few questions:
> 
> It appears that all these pools have Intellibright lights, is that true?

Yes
> 0D-BF-7F and 0F-5A-03 have something in common, but it's an unknown flag. Could you guess/know what it is?

It’s probably the spa side remote?
